CREATE TABLE document_ops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    rev INT NOT NULL,
    base_rev INT NOT NULL,
    actor_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    op_json JSON NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (doc_id, rev)
);

CREATE TABLE document_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    rev INT NOT NULL,
    snapshot_json JSON NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (doc_id, rev)
);

CREATE INDEX idx_document_ops_doc_rev ON document_ops(doc_id, rev);
CREATE INDEX idx_document_snapshots_doc_rev ON document_snapshots(doc_id, rev);
